name: Docker Build and Push

on:
  push:
    branches: [ "use-build-stages" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest-xlarge
    permissions:
      packages: write

    strategy:
      matrix:
        model_variant: 
          - Qwen2.5-VL-3B-Instruct
          # - Qwen2.5-VL-7B-Instruct
          # - Qwen2.5-VL-72B-Instruct

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.model_variant }}-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.model_variant }}-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract model variant
        id: extract_model
        run: echo "MODEL_VARIANT=$(echo '${{ matrix.model_variant }}' | sed -E 's/.*-([0-9]+B)-.*/\1/' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          tags: |
            ghcr.io/${{ github.repository_owner }}/qwen2.5-vl:${{ env.MODEL_VARIANT }}
          build-args: |
            QWEN_MODEL=${{ matrix.model_variant }}
