name: Docker Build and Push

on:
  push:
    branches: [ "use-build-stages" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    strategy:
      matrix:
        model_variant: 
          - Qwen2.5-VL-3B-Instruct
          # - Qwen2.5-VL-7B-Instruct
          # - Qwen2.5-VL-72B-Instruct 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/qwen2.5-vl-inference-openai:${{ matrix.model_variant }}-${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/qwen2.5-vl-inference-openai:${{ matrix.model_variant }}-latest
          build-args: |
            QWEN_MODEL=${{ matrix.model_variant }}
